using MySql.Data.MySqlClient;
using OminHub.Core.Abstractions;
using OminHub.Core.Models;

namespace OminHub.Infrastructure.Repositories;

public sealed class VideoThumbnailRepository : IVideoThumbnailRepository
{
    private readonly string _connectionString;

    public VideoThumbnailRepository(string connectionString)
    {
        _connectionString = connectionString;
    }

    private MySqlConnection GetConn()
        => new MySqlConnection(_connectionString);

    public async Task InsertInitialAsync(
        long videoId,
        IEnumerable<VideoThumbnailInput> thumbnails,
        CancellationToken ct
    )
    {
        using var cnn = GetConn();
        await cnn.OpenAsync(ct);
        using var tx = await cnn.BeginTransactionAsync(ct);

        foreach (var t in thumbnails)
        {
            using var cmd = new MySqlCommand(
                @"INSERT INTO video_thumbnails
                  (VideoId, FilePath, IsPrimary, OrderIndex, IsAutoGenerated)
                  VALUES (@Vid, @Path, @Primary, @Order, 0)",
                cnn,
                (MySqlTransaction)tx
            );

            cmd.Parameters.AddWithValue("@Vid", videoId);
            cmd.Parameters.AddWithValue("@Path", t.FilePath);
            cmd.Parameters.AddWithValue("@Primary", t.IsPrimary);
            cmd.Parameters.AddWithValue("@Order", t.OrderIndex);

            await cmd.ExecuteNonQueryAsync(ct);
        }

        await tx.CommitAsync(ct);
    }
}
