namespace OminHub.Core.Models
{
    public class VideoThumbnailInput
    {
        public long? Id { get; set; }              // null = nuevo
        public string FilePath { get; set; } = null!;
        public bool IsPrimary { get; set; }
        public byte OrderIndex { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
