using System;
using System.Data;
using System.Data.Common;

namespace OminHub.Api.Model
{
    public class VideoThumbnail : IMySqlMappable<VideoThumbnail>
    {
        public long Id { get; set; }
        public long VideoId { get; set; }
        public string FilePath { get; set; } = null!;
        public bool IsPrimary { get; set; }
        public byte OrderIndex { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? LastShownAt { get; set; }
        public int ServeWeight { get; set; }
        public bool IsAutoGenerated { get; set; }

        public VideoThumbnail FromReader(DbDataReader rd)
        {
            return new VideoThumbnail
            {
                Id = rd.GetInt64("Id"),
                VideoId = rd.GetInt64("VideoId"),
                FilePath = rd.GetString("FilePath"),
                IsPrimary = rd.GetBoolean("IsPrimary"),
                OrderIndex = rd.GetByte("OrderIndex"),
                CreatedAt = rd.GetDateTime("CreatedAt"),
                LastShownAt = rd.IsDBNull("LastShownAt") ? null : rd.GetDateTime("LastShownAt"),
                ServeWeight = rd.GetInt32("ServeWeight"),
                IsAutoGenerated = rd.GetBoolean("IsAutoGenerated")
            };
        }
    }
}
